

name: CI


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

   workflow_dispatch:

jobs:
  
  build:
   
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v1

      
      - name: Run a one-line script
        run: echo Hello, world!

      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
       
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python model/train.py

      - name: Evaluate model
        run: |
          python model/evaluate.py

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests